version: '2'

# docker run --hostname=quickstart.cloudera --privileged=true -m 10g -t -d -i -p 8888:8888 -p 80:80 -p 7180:7180 cloudera/quickstart:latest /usr/bin/docker-quickstart
# docker run --hostname=quickstart.cloudera --privileged=true -m 10g -t -d -i -p 8888:8888 -p 10080:80 -p 17180:7180 cloudera/quickstart:latest /usr/bin/docker-quickstart
# docker run --hostname=server01.hadoop.com --privileged=true -m 10g -t -d -i -p 8888:8888 -p 10080:80 -p 17180:7180 cloudera/quickstart:latest /usr/bin/docker-quickstart
# docker run --hostname=server01.hadoop.com --privileged=true -m 10g -t -d -i -p 18888:8888 -p 10080:80 -p 17180:7180 cloudera/quickstart:latest /bin/bash -c "/usr/bin/docker-quickstart & /home/cloudera/cloudera-manager --enterprise"

services:
  hadoop01:
    container_name: hadoop01
    # hostname: server01.hadoop.com
    hostname: quickstart.cloudera
    privileged: true
    mem_limit: 10g
    # image: paternallove/cloudera-manager:latest
    image: cloudera/quickstart:latest
    networks:
      myhadoopbr:
        ipv4_address: 192.168.56.101
    extra_hosts:
      # - "quickstart.cloudera:192.168.56.101"
      # - "server01.hadoop.com:192.168.56.101"
      - "server02.hadoop.com:192.168.56.102"
      - "server03.hadoop.com:192.168.56.103"
    tty: true
    command: bash -c "/usr/bin/docker-quickstart & /home/cloudera/cloudera-manager --enterprise & /bin/bash"
    # command: bash -c "/home/cloudera/cloudera-manager --enterprise & /bin/bash"
    ports:
      - 8888:8888
      - 7180:7180
      - 80:80
    # command: bash -c "service sshd start"
    # command: /etc/init.d/sshd restart
    # links:
    #   - hadoop01
    #   - hadoop02
    #   - hadoop03

  hadoop02:
    container_name: hadoop02
    hostname: server02.hadoop.com
    mem_limit: 10g
    #image: paternallove/centos9.8-hadoop:latest
    image: paternallove/cloudera-host:latest
    networks:
      myhadoopbr:
        ipv4_address: 192.168.56.102
    extra_hosts:
      - "quickstart.cloudera:192.168.56.101"
      # - "server01.hadoop.com:192.168.56.101"
      # - "server02.hadoop.com:192.168.56.102"
      - "server03.hadoop.com:192.168.56.103"
    depends_on:
      - hadoop01
    tty: true
    command: bash -c "exec /sk/start.sh & /bin/bash"
    # links:
    #   - hadoop01
    #   - hadoop02
    #   - hadoop03

  hadoop03:
    container_name: hadoop03
    hostname: server03.hadoop.com
    mem_limit: 10g
    # image: paternallove/centos9.8-hadoop:latest
    image: paternallove/cloudera-host:latest
    networks:
      myhadoopbr:
        ipv4_address: 192.168.56.103
    extra_hosts:
      - "quickstart.cloudera:192.168.56.101"
      # - "server01.hadoop.com:192.168.56.101"
      - "server02.hadoop.com:192.168.56.102"
      # - "server03.hadoop.com:192.168.56.103"
    depends_on:
      - hadoop02
    tty: true
    command: bash -c "exec /sk/start.sh & /bin/bash"
    # links:
    #   - hadoop01
    #   - hadoop02
    #   - hadoop03

networks:
  myhadoopbr:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.56.0/24
         gateway: 192.168.56.1
